### ISSUE TITLE
请教：vue-admin-template下安装报错

### ISSUE THREAD

**Issue by idragonet** [code-farmer-i/vue-markdown-editor#178]
PS E:\Vue\vue-admin-template> npm i @kangc/v-md-editor -S
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-admin-template@4.4.0
npm ERR! Found: vue@2.6.10
npm ERR! node_modules/vue
npm ERR!   vue@"2.6.10" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.6.11" from @kangc/v-md-editor@1.7.11
npm ERR! node_modules/@kangc/v-md-editor
npm ERR!   @kangc/v-md-editor@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\longzhang\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\longzhang\AppData\Local\npm-cache\_logs\2022-06-13T13_47_35_999Z-debug.log

--
2022-06-13T13_47_35_999Z-debug.log：
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\longzhang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i',
0 verbose cli   '@kangc/v-md-editor',
0 verbose cli   '-S'
0 verbose cli ]
1 info using npm@7.10.0
2 info using node@v14.17.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\longzhang\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:E:\Vue\vue-admin-template\.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:C:\Users\longzhang\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\longzhang\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 10ms
18 timing npm:load:configload Completed in 10ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 1ms
21 timing npm:load:cleanupLog Completed in 1ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 0ms
24 timing npm:load Completed in 16ms
25 timing config:load:flatten Completed in 2ms
26 timing arborist:ctor Completed in 1ms
27 timing idealTree:init Completed in 748ms
28 timing idealTree:userRequests Completed in 7ms
29 silly idealTree buildDeps
30 silly fetch manifest @kangc/v-md-editor@*
31 http fetch GET 200 https://registry.npmjs.org/@kangc%2fv-md-editor 112ms (from cache)
32 silly fetch manifest vue@2.6.10
33 timing arborist:ctor Completed in 0ms
34 http fetch GET 304 https://registry.npmjs.org/vue 2486ms (from cache)
35 silly fetch manifest vue@^2.6.11
36 timing idealTree Completed in 3377ms
37 timing command:install Completed in 3386ms
38 verbose stack Error: unable to resolve dependency tree
38 verbose stack     at Arborist.[failPeerConflict] (C:\Users\longzhang\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1210:25)
38 verbose stack     at Arborist.[loadPeerSet] (C:\Users\longzhang\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1187:34)
38 verbose stack     at async Arborist.[buildDepStep] (C:\Users\longzhang\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:891:11)
38 verbose stack     at async Arborist.buildIdealTree (C:\Users\longzhang\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:217:7)
38 verbose stack     at async Promise.all (index 1)
38 verbose stack     at async Arborist.reify (C:\Users\longzhang\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:134:5)
38 verbose stack     at async Install.install (C:\Users\longzhang\AppData\Roaming\npm\node_modules\npm\lib\install.js:137:5)
39 verbose cwd E:\Vue\vue-admin-template
40 verbose Windows_NT 10.0.22621
41 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\longzhang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "@kangc/v-md-editor" "-S"
42 verbose node v14.17.0
43 verbose npm  v7.10.0
44 error code ERESOLVE
45 error ERESOLVE unable to resolve dependency tree
46 error
47 error While resolving: [1mvue-admin-template[22m@[1m4.4.0[22m
47 error Found: [1mvue[22m@[1m2.6.10[22m[2m[22m
47 error [2mnode_modules/vue[22m
47 error   [1mvue[22m@"[1m2.6.10[22m" from the root project
47 error
47 error Could not resolve dependency:
47 error [35mpeer[39m [1mvue[22m@"[1m^2.6.11[22m" from [1m@kangc/v-md-editor[22m@[1m1.7.11[22m[2m[22m
47 error [2mnode_modules/@kangc/v-md-editor[22m
47 error   [1m@kangc/v-md-editor[22m@"[1m*[22m" from the root project
47 error
47 error Fix the upstream dependency conflict, or retry
47 error this command with --force, or --legacy-peer-deps
47 error to accept an incorrect (and potentially broken) dependency resolution.
47 error
47 error See C:\Users\longzhang\AppData\Local\npm-cache\eresolve-report.txt for a full report.
48 verbose exit 1

**Comment by idragonet** [comment]
解决了 升级到VUE 2.6.11即可。
