### ISSUE TITLE
Vue 3 单独使用预览组件报错

### ISSUE THREAD

**Issue by lizehua-cn** [code-farmer-i/vue-markdown-editor#194]
本地配置
```
import VMdPreview from '@kangc/v-md-editor/lib/preview'
import '@kangc/v-md-editor/lib/style/preview.css'
import vuepressTheme from '@kangc/v-md-editor/lib/theme/vuepress.js'
import '@kangc/v-md-editor/lib/theme/style/vuepress.css'
import hljs from 'highlight.js'
VMdPreview.use(vuepressTheme, {
  Hljs: hljs
})
```
版本
```
"@kangc/v-md-editor": "^2.3.15",
"highlight.js": "^11.6.0",
```
报错
```
preview.js?4e08:1 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.eval (preview.js?4e08:1:1)
    at n (preview.js?4e08:1:1)
    at Module.eval (preview.js?4e08:1:1)
    at n (preview.js?4e08:1:1)
    at eval (preview.js?4e08:1:1)
    at eval (preview.js?4e08:1:1)
    at eval (preview.js?4e08:1:1)
    at eval (preview.js?4e08:1:1)
    at ./node_modules/.pnpm/@kangc+v-md-editor@1.7.11_vue@3.2.38/node_modules/@kangc/v-md-editor/lib/preview.js (chunk-vendors.js:20059:1)
    at __webpack_require__ (app.js:854:30)
```

**Comment by lizehua-cn** [comment]
#### vuepress 主题
> markdown 解析使用 [markdown-it](https://github.com/markdown-it/markdown-it)来实现，代码块解析使用 [prism](https://github.com/PrismJS/prism)来实现。
#### github 主题
> markdown 解析使用 [markdown-it](https://github.com/markdown-it/markdown-it)来实现，代码块解析使用 [highlight.js](https://github.com/highlightjs/highlight.js)来实现。

[参照 v-md-editor 文档](https://ckang1229.gitee.io/vue-markdown-editor/zh/theme/vuepress.html#%E4%BB%8B%E7%BB%8D)

**Comment by b-yp** [comment]
@lizehua-cn     你的问题是解决了吗，我遇到了同样的报错，还没解决
