### ISSUE TITLE
在预览模式下 添加图片 尺寸超过预览界面会提示报错

### ISSUE THREAD

**Issue by wr-hub** [code-farmer-i/vue-markdown-editor#241]
Uncaught runtime errors:
×
ERROR
ResizeObserver loop limit exceeded
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:299:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:318:7)

**Comment by wr-hub** [comment]
开发环境下会报错，打包后正常

**Comment by code-farmer-i** [comment]
默认是有个样式限制了图片的max-width: 100%，文档示例中无法复现

**Comment by wr-hub** [comment]
找到原因了开发环境下 webpack-dev-server 这个模版会频繁 调用ResizeObserver这个。 不仅是图片，预览模式下，只要填充的内容超过高度，就会报错。
